/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author jatawatsafe
 */
public class HomePage extends javax.swing.JFrame {
    /**
     * Creates new form TemplateJFrame
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        topic = new javax.swing.JLabel();
        jPanel01 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        game1 = new javax.swing.JLabel();
        jPanel02 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        game2 = new javax.swing.JLabel();
        jPanel03 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        game3 = new javax.swing.JLabel();
        jPanel04 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        game4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IT OPENHOUSE 2019");
        setMaximumSize(new java.awt.Dimension(846, 602));
        setMinimumSize(new java.awt.Dimension(846, 602));
        setName("IT OPENHOUSE 2019"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(846, 602));

        kGradientPanel1.setkEndColor(new java.awt.Color(238, 156, 167));
        kGradientPanel1.setkGradientFocus(90);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 221, 225));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(846, 602));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(846, 602));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(846, 602));

        topic.setFont(new java.awt.Font("Arial", 1, 72)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/test2.png"))); // NOI18N

        jPanel01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel01.setPreferredSize(new java.awt.Dimension(144, 196));
        jPanel01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionPrimeNumber(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited01(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered01(evt);
            }
        });
        jPanel01.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mini Game 1");
        jPanel01.add(jLabel1, java.awt.BorderLayout.CENTER);

        game1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/game1.png"))); // NOI18N
        game1.setText(" ");
        jPanel01.add(game1, java.awt.BorderLayout.PAGE_START);

        jPanel02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel02.setPreferredSize(new java.awt.Dimension(144, 196));
        jPanel02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionGuessNumber(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited02(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered02(evt);
            }
        });
        jPanel02.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mini Game 2");
        jPanel02.add(jLabel4, java.awt.BorderLayout.CENTER);

        game2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/game2.png"))); // NOI18N
        game2.setText(" ");
        jPanel02.add(game2, java.awt.BorderLayout.PAGE_START);

        jPanel03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel03.setPreferredSize(new java.awt.Dimension(144, 196));
        jPanel03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionWeightConverter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removed03(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered03(evt);
            }
        });
        jPanel03.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mini Game 3");
        jPanel03.add(jLabel6, java.awt.BorderLayout.CENTER);

        game3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/game3.png"))); // NOI18N
        game3.setText(" ");
        jPanel03.add(game3, java.awt.BorderLayout.PAGE_START);

        jPanel04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel04.setPreferredSize(new java.awt.Dimension(144, 196));
        jPanel04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionMultipleChoice(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exited04(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entered04(evt);
            }
        });
        jPanel04.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mini Game 4");
        jPanel04.add(jLabel5, java.awt.BorderLayout.CENTER);

        game4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/game4.png"))); // NOI18N
        game4.setText("   ");
        jPanel04.add(game4, java.awt.BorderLayout.PAGE_START);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/logoSIT.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Powered by");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo)
                .addGap(304, 304, 304))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))))
        );

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPrimeNumber(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionPrimeNumber
        new PrimeNumberChecker().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_actionPrimeNumber

    private void actionGuessNumber(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionGuessNumber
        new GuessTheNumber().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_actionGuessNumber

    private void actionWeightConverter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionWeightConverter
        new StarCalculate().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_actionWeightConverter

    private void actionMultipleChoice(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMultipleChoice
        new DidYouKnow01().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_actionMultipleChoice

    private void entered01(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered01
        setButtonColor(jPanel01);
    }//GEN-LAST:event_entered01

    private void exited01(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited01
        resetButtonColor(jPanel01);
    }//GEN-LAST:event_exited01

    private void entered02(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered02
        setButtonColor(jPanel02);
    }//GEN-LAST:event_entered02

    private void exited02(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited02
        resetButtonColor(jPanel02);
    }//GEN-LAST:event_exited02

    private void entered03(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered03
        setButtonColor(jPanel03);
    }//GEN-LAST:event_entered03

    private void removed03(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removed03
        resetButtonColor(jPanel03);
    }//GEN-LAST:event_removed03

    private void entered04(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entered04
        setButtonColor(jPanel04);
    }//GEN-LAST:event_entered04

    private void exited04(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exited04
        resetButtonColor(jPanel04);
    }//GEN-LAST:event_exited04

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    
    public void setButtonColor(JLayeredPane panel) {
        panel.setBackground(Color.ORANGE);
    }

    public void resetButtonColor(JLayeredPane panel) {
        panel.setBackground(Color.WHITE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel game1;
    private javax.swing.JLabel game2;
    private javax.swing.JLabel game3;
    private javax.swing.JLabel game4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jPanel01;
    private javax.swing.JLayeredPane jPanel02;
    private javax.swing.JLayeredPane jPanel03;
    private javax.swing.JLayeredPane jPanel04;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel topic;
    // End of variables declaration//GEN-END:variables
}
